package_update: true
package_upgrade: true

timezone: Europe/Berlin

manage_etc_hosts: true

packages:
  - docker.io
  - curl
  - git
  - snapd

users:
  - default

  - name: patrick
    groups:
      - sudo
    sudo:
      - ALL=(ALL) NOPASSWD:ALL
    ssh_import_id:
      - gh:poberherr
    uid: 1001

  - name: max
    groups:
      - sudo
    sudo:
      - ALL=(ALL) NOPASSWD:ALL
    ssh_import_id:
      - gh:fugufisch
    uid: 1002

  - name: jens
    groups:
      - sudo
    sudo:
      - ALL=(ALL) NOPASSWD:ALL
    ssh_import_id:
      - gh:derHahn
    uid: 1003

write_files:
  - path: /etc/netplan/01-netplan.yaml
    content: |
      network:
        version: 2
        ethernets:
          eth0:
            nameservers:
              addresses:
                - 1.1.1.1
                - 1.0.0.1
    permissions: "0600"

runcmd:
  - netplan apply
  - sed -i '/PermitRootLogin/d' /etc/ssh/sshd_config
  - echo "PermitRootLogin no" >> /etc/ssh/sshd_config
  - systemctl restart sshd
  - snap install btop
  - reboot
