#cloud-config
write_files:
  - path: /etc/clickhouse-server/config.d/networking.xml
    content: |
      <?xml version="1.0"?>
      <clickhouse>
          <network>
              <listen_host>::</listen_host>
              <listen_host>0.0.0.0</listen_host>
              <listen_try>1</listen_try>
              <max_connections>4096</max_connections>
              <keep_alive_timeout>3</keep_alive_timeout>
              <tcp_port>9000</tcp_port>
              <http_port>8123</http_port>
          </network>
      </clickhouse>
    permissions: "0644"

  - path: /etc/clickhouse-server/config.xml
    content: |
      <?xml version="1.0"?>
      <clickhouse>
          <logger>
              <level>trace</level>
              <log>/var/log/clickhouse-server/clickhouse-server.log</log>
              <errorlog>/var/log/clickhouse-server/clickhouse-server.err.log</errorlog>
          </logger>
          
          <path>/mnt/HC_Volume_101756196/</path>
          <tmp_path>/mnt/HC_Volume_101756196/tmp/</tmp_path>
          <user_files_path>/var/lib/clickhouse/user_files/</user_files_path>
          <users_config>users.xml</users_config>
          <default_profile>default</default_profile>
          <default_database>default</default_database>
      </clickhouse>
    permissions: "0644"

  - path: /etc/clickhouse-server/users.xml
    content: |
      <?xml version="1.0"?>
      <clickhouse>
          <users>
              <default>
                  <password></password>
                  <networks>
                      <ip>::/0</ip>
                  </networks>
                  <profile>default</profile>
                  <quota>default</quota>
              </default>
          </users>
          <profiles>
              <default>
                  <max_memory_usage>10000000000</max_memory_usage>
                  <use_uncompressed_cache>0</use_uncompressed_cache>
                  <load_balancing>random</load_balancing>
              </default>
          </profiles>
          <quotas>
              <default>
                  <interval>
                      <duration>3600</duration>
                      <queries>0</queries>
                      <errors>0</errors>
                      <result_rows>0</result_rows>
                      <read_rows>0</read_rows>
                      <execution_time>0</execution_time>
                  </interval>
              </default>
          </quotas>
      </clickhouse>
    permissions: "0644"
